### ISSUE TITLE
Release v0.1.5

### ISSUE THREAD

**Issue by Mossaka** [Mossaka/containerd-wasm-shims#11]
Just want to clarify the work items we want to fix before releasing v0.1.5
- [x] #14   fix the termination issue by implementing `kill()`
- [x] #9  implement the new generic engine API from `runwasi`
- [x] #3  connect wasmtime engine IO with containerd
- [ ] (optional) Migrate to `runwasi`
